### ISSUE TITLE
grub and wimboot efi patches

### ISSUE THREAD

**Issue by mj-p** [grub4dos/wimboot#1]
Hey @a1ive
I saw your work on wimboot with efi in your grub repo.
Would it be possible to share patches needed for wimboot so it can be applied to the latest wimboot version?
Maybe even patches for grub so they can be applied to the latest version as well?
All in all it would be great to be able to use up-to-date versions of grub and wimboot now and in the future.

**Comment by a1ive** [comment]
1. Boot patched iPXE wimboot binary from patched GRUB.
2. Port wimboot to GRUB as a module (wimboot.mod).
Which of these two solutions do you want?

**Comment by mj-p** [comment]
Personally I am fine with either one. Which one do you think would be easier to maintain in future wimboot and grub updates? I would probably lean to that solution.

**Comment by a1ive** [comment]
Solution 1: Both wimboot and grub2 need to be modified, but with less code. The patched wimboot has problems booting on some computers.
Solution 2: Since wimboot has been ported to grub2, only grub2 needs to be modified subsequently. But there is more code to modify.

**Comment by a1ive** [comment]
For solution 1, you need to patch grub2 to add support for Linux EFI handover protocol:
https://github.com/rhboot/grub2/commit/4c4c5fd57a931ef6e67503d5e7f447bd09463580
and then add newc initrd support:
https://github.com/a1ive/grub/commit/360d00bd6964ccd9b2d6c06bcddafe02bebe11fd#diff-609b7d8cbe498c14621d3cd0cc9cecbc8a286fde2f6c053509ea5d51916ad8ce
You should also patch wimboot : https://github.com/Sporesirius/wimboot

**Comment by mj-p** [comment]
Well if solution 1 has problems booting on some computers then it's not for me. I will look more into the other solution.
Thanks a bunch for your time and ressources.
